services:
  - type: web
    name: url-shortener-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: MONGO_URI
        sync: false  # Set this manually in Render's dashboard
